permalink: /:year/:month/:title.html
exclude: [ Gemfile, Gemfile.lock, Rakefile, README.md, README_POSTS.md ]
future: false
lsi: true # Produces an index for related posts.
paginate: 10
plugins: ./_plugins

brand: mhack

author:
  name: Marcos Hack
  email: marcoshack@gmail.com
  twitter: marcoshack
  github: marcoshack
  linkedin: marcoshack
  google_plus: 101876381204467415756

title_sufix: '- Marcos Hack'

disqus:
  shortname: mhack

google_analytics:
  id: UA-6981296-7

github:
  ribbon: false

copyright: '© 2013 Marcos Hack. All rights reserved.'
