permalink: /:year/:month/:title.html

exclude:
  - Gemfile
  - Gemfile.lock
  - README

future: false

# Produces an index for related posts.
lsi: true

authors:
  mhack:
    name: Marcos Hack
    display_name: Marcos Hack
    email: marcoshack@gmail.com
    twitter: marcoshack
    github: marcoshack
