permalink: /:year/:month/:title.html

exclude: [ Gemfile, Gemfile.lock, Rakefile, README.md ]

future: false
lsi: true # Produces an index for related posts.
paginate: 3

authors:
  mhack:
    name: Marcos Hack
    display_name: Marcos Hack
    email: marcoshack@gmail.com
    twitter: marcoshack
    github: marcoshack
